version: '3'

services:
  dev:
    build: ./services/dev
    environment:
      - GOOGLE_CLOUD_REGION=${GOOGLE_CLOUD_REGION}
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
      - TERRAFORM_BACKEND_BUCKET=${TERRAFORM_BACKEND_BUCKET}
      - TERRAFORM_DOMAIN=${TERRAFORM_DOMAIN}
    tty: true
    volumes:
      - ../:/workspace
